### PR TITLE
Found some leftover use of Point3 that caused the code not to build.

### PR DESCRIPTION
**Pull request by thelazyone**
I am fairly new to pull requests so apologies in advance if this is not the right way.
I was going to test the new voxel remesh (or at least check the progress) and got some compilation errors from the clean checkout of the vdb branch. 

By changing a Point3 into a Vector3 and remove some .coordinates here and there it seems to build OK.

This is in line with your last commit b23cec9cbdd22e0f205ef1b62d604e3a4ba8e20f

### CODE REVIEW

**Comment by thelazyone** [comment]
Worth noting that even with the fix the tests don't work. The kind of errors are in the marchincube algo, of the kind: 

`thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 25', C:\Projects\baby_shark\src\voxel\meshing\marching_cubes.rs:239:41`

It seems like the objects of the type TILING_EDGES_13_4 now have one extra dimension that is not addressed correctly by the indexes

**Comment by dima634** [comment]
> Worth noting that even with the fix the tests don't work. The kind of errors are in the marchincube algo, of the kind:
> 
> `thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 25', C:\Projects\baby_shark\src\voxel\meshing\marching_cubes.rs:239:41`
> 
> It seems like the objects of the type TILING_EDGES_13_4 now have one extra dimension that is not addressed correctly by the indexes

Could you share code to reproduce this?

**Comment by thelazyone** [comment]
Sure thing! I'm actually using your voxel.rs code with this STL: I just changed the line from caesar.stl to head.stl.
[head.zip](https://github.com/dima634/baby_shark/files/14041824/head.zip)

This is the error. It's slightly different from the one i mentioned this morning because i reproduced the issue on another machine, but it should lead to the same kind of problem.

image

**Comment by thelazyone** [comment]
Glad to help. 
On one side, i'm dreaming of an optimized remesher for miniatures sculpting (things are SLOW in blender because the decimate is not written in C), on another i'd love to integratea simple protocol web visualizer i'm (clumsly) trying to do into baby_shark. 

https://github.com/thelazyone/3d-external-visualizer

**Pull request merged**
